// Generated by ProtoGen, Version=2.4.1.473, Culture=neutral, PublicKeyToken=55f7125234beb589.  DO NOT EDIT!
#pragma warning disable 1591, 0612
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace swgemurpcserver.rpc {
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public static partial class CharacterDetails {
  
    #region Extension registration
    public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
    }
    #endregion
    #region Static variables
    internal static pbd::MessageDescriptor internal__static_swgemurpcserver_rpc_SWGEmuCharacterDetail__Descriptor;
    internal static pb::FieldAccess.FieldAccessorTable<global::swgemurpcserver.rpc.SWGEmuCharacterDetail, global::swgemurpcserver.rpc.SWGEmuCharacterDetail.Builder> internal__static_swgemurpcserver_rpc_SWGEmuCharacterDetail__FieldAccessorTable;
    internal static pbd::MessageDescriptor internal__static_swgemurpcserver_rpc_SWGEmuCharacterStructureItem__Descriptor;
    internal static pb::FieldAccess.FieldAccessorTable<global::swgemurpcserver.rpc.SWGEmuCharacterStructureItem, global::swgemurpcserver.rpc.SWGEmuCharacterStructureItem.Builder> internal__static_swgemurpcserver_rpc_SWGEmuCharacterStructureItem__FieldAccessorTable;
    internal static pbd::MessageDescriptor internal__static_swgemurpcserver_rpc_GetCharacterDetailsRequest__Descriptor;
    internal static pb::FieldAccess.FieldAccessorTable<global::swgemurpcserver.rpc.GetCharacterDetailsRequest, global::swgemurpcserver.rpc.GetCharacterDetailsRequest.Builder> internal__static_swgemurpcserver_rpc_GetCharacterDetailsRequest__FieldAccessorTable;
    internal static pbd::MessageDescriptor internal__static_swgemurpcserver_rpc_GetCharacterDetailsResponse__Descriptor;
    internal static pb::FieldAccess.FieldAccessorTable<global::swgemurpcserver.rpc.GetCharacterDetailsResponse, global::swgemurpcserver.rpc.GetCharacterDetailsResponse.Builder> internal__static_swgemurpcserver_rpc_GetCharacterDetailsResponse__FieldAccessorTable;
    #endregion
    #region Descriptor
    public static pbd::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbd::FileDescriptor descriptor;
    
    static CharacterDetails() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          "ChZDaGFyYWN0ZXJEZXRhaWxzLnByb3RvEhNzd2dlbXVycGNzZXJ2ZXIucnBj" + 
          "GhNJbnZlbnRvcnlJdGVtLnByb3RvIq4DChVTV0dFbXVDaGFyYWN0ZXJEZXRh" + 
          "aWwSEQoJb2JqZWN0X2lkGAEgAigGEhIKCmFjY291bnRfaWQYAiACKAcSEgoK" + 
          "Zmlyc3RfbmFtZRgDIAIoCRIQCghzdXJfbmFtZRgEIAIoCRIUCgxiYW5rX2Ny" + 
          "ZWRpdHMYBSABKAcSFAoMY2FzaF9jcmVkaXRzGAYgASgHEhMKC2Jhc2VfaGVh" + 
          "bHRoGAcgASgHEhMKC2Jhc2VfYWN0aW9uGAggASgHEhEKCWJhc2VfbWluZBgK" + 
          "IAEoBxIRCgliaW9ncmFwaHkYCyABKAkSFwoPcmVtYWluaW5nX3Bsb3RzGAwg" + 
          "ASgFEhcKD21heGltdW1pbV9wbG90cxgNIAEoBRINCgV0aXRsZRgOIAEoCRJE" + 
          "Cg9pbnZlbnRvcnlfaXRlbXMYFCADKAsyKy5zd2dlbXVycGNzZXJ2ZXIucnBj" + 
          "LkNoYXJhY3RlckludmVudG9yeUl0ZW0SRQoKc3RydWN0dXJlcxgVIAMoCzIx" + 
          "LnN3Z2VtdXJwY3NlcnZlci5ycGMuU1dHRW11Q2hhcmFjdGVyU3RydWN0dXJl" + 
          "SXRlbSJcChxTV0dFbXVDaGFyYWN0ZXJTdHJ1Y3R1cmVJdGVtEhEKCW9iamVj" + 
          "dF9pZBgBIAIoBhITCgtvYmplY3RfbmFtZRgCIAIoCRIUCgxkaXNwbGF5X25h" + 
          "bWUYAyACKAkikQEKGkdldENoYXJhY3RlckRldGFpbHNSZXF1ZXN0EhIKCmFj" + 
          "Y291bnRfaWQYASACKAcSEQoJb2JqZWN0X2lkGAIgASgGEhEKCWdhbGF4eV9p" + 
          "ZBgDIAEoBxISCgpmaXJzdF9uYW1lGAcgASgJEhAKCHN1cl9uYW1lGAggASgJ" + 
          "EhMKC2dhbGF4eV9uYW1lGAkgASgJImQKG0dldENoYXJhY3RlckRldGFpbHNS" + 
          "ZXNwb25zZRJFChFjaGFyYWN0ZXJfZGV0YWlscxgBIAMoCzIqLnN3Z2VtdXJw" + 
          "Y3NlcnZlci5ycGMuU1dHRW11Q2hhcmFjdGVyRGV0YWlsMpkBCh1TV0dFbXVD" + 
          "aGFyYWN0ZXJEZXRhaWxzU2VydmljZRJ4ChNHZXRDaGFyYWN0ZXJEZXRhaWxz" + 
          "Ei8uc3dnZW11cnBjc2VydmVyLnJwYy5HZXRDaGFyYWN0ZXJEZXRhaWxzUmVx" + 
          "dWVzdBowLnN3Z2VtdXJwY3NlcnZlci5ycGMuR2V0Q2hhcmFjdGVyRGV0YWls" + 
          "c1Jlc3BvbnNlQgOAAQE=");
      pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
        descriptor = root;
        internal__static_swgemurpcserver_rpc_SWGEmuCharacterDetail__Descriptor = Descriptor.MessageTypes[0];
        internal__static_swgemurpcserver_rpc_SWGEmuCharacterDetail__FieldAccessorTable = 
            new pb::FieldAccess.FieldAccessorTable<global::swgemurpcserver.rpc.SWGEmuCharacterDetail, global::swgemurpcserver.rpc.SWGEmuCharacterDetail.Builder>(internal__static_swgemurpcserver_rpc_SWGEmuCharacterDetail__Descriptor,
                new string[] { "ObjectId", "AccountId", "FirstName", "SurName", "BankCredits", "CashCredits", "BaseHealth", "BaseAction", "BaseMind", "Biography", "RemainingPlots", "MaximumimPlots", "Title", "InventoryItems", "Structures", });
        internal__static_swgemurpcserver_rpc_SWGEmuCharacterStructureItem__Descriptor = Descriptor.MessageTypes[1];
        internal__static_swgemurpcserver_rpc_SWGEmuCharacterStructureItem__FieldAccessorTable = 
            new pb::FieldAccess.FieldAccessorTable<global::swgemurpcserver.rpc.SWGEmuCharacterStructureItem, global::swgemurpcserver.rpc.SWGEmuCharacterStructureItem.Builder>(internal__static_swgemurpcserver_rpc_SWGEmuCharacterStructureItem__Descriptor,
                new string[] { "ObjectId", "ObjectName", "DisplayName", });
        internal__static_swgemurpcserver_rpc_GetCharacterDetailsRequest__Descriptor = Descriptor.MessageTypes[2];
        internal__static_swgemurpcserver_rpc_GetCharacterDetailsRequest__FieldAccessorTable = 
            new pb::FieldAccess.FieldAccessorTable<global::swgemurpcserver.rpc.GetCharacterDetailsRequest, global::swgemurpcserver.rpc.GetCharacterDetailsRequest.Builder>(internal__static_swgemurpcserver_rpc_GetCharacterDetailsRequest__Descriptor,
                new string[] { "AccountId", "ObjectId", "GalaxyId", "FirstName", "SurName", "GalaxyName", });
        internal__static_swgemurpcserver_rpc_GetCharacterDetailsResponse__Descriptor = Descriptor.MessageTypes[3];
        internal__static_swgemurpcserver_rpc_GetCharacterDetailsResponse__FieldAccessorTable = 
            new pb::FieldAccess.FieldAccessorTable<global::swgemurpcserver.rpc.GetCharacterDetailsResponse, global::swgemurpcserver.rpc.GetCharacterDetailsResponse.Builder>(internal__static_swgemurpcserver_rpc_GetCharacterDetailsResponse__Descriptor,
                new string[] { "CharacterDetails", });
        return null;
      };
      pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
          new pbd::FileDescriptor[] {
          global::swgemurpcserver.rpc.InventoryItem.Descriptor, 
          }, assigner);
    }
    #endregion
    
  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public sealed partial class SWGEmuCharacterDetail : pb::GeneratedMessage<SWGEmuCharacterDetail, SWGEmuCharacterDetail.Builder> {
    private SWGEmuCharacterDetail() { }
    private static readonly SWGEmuCharacterDetail defaultInstance = new SWGEmuCharacterDetail().MakeReadOnly();
    private static readonly string[] _sWGEmuCharacterDetailFieldNames = new string[] { "account_id", "bank_credits", "base_action", "base_health", "base_mind", "biography", "cash_credits", "first_name", "inventory_items", "maximumim_plots", "object_id", "remaining_plots", "structures", "sur_name", "title" };
    private static readonly uint[] _sWGEmuCharacterDetailFieldTags = new uint[] { 21, 45, 69, 61, 85, 90, 53, 26, 162, 104, 9, 96, 170, 34, 114 };
    public static SWGEmuCharacterDetail DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override SWGEmuCharacterDetail DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override SWGEmuCharacterDetail ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::swgemurpcserver.rpc.CharacterDetails.internal__static_swgemurpcserver_rpc_SWGEmuCharacterDetail__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<SWGEmuCharacterDetail, SWGEmuCharacterDetail.Builder> InternalFieldAccessors {
      get { return global::swgemurpcserver.rpc.CharacterDetails.internal__static_swgemurpcserver_rpc_SWGEmuCharacterDetail__FieldAccessorTable; }
    }
    
    public const int ObjectIdFieldNumber = 1;
    private bool hasObjectId;
    private ulong objectId_;
    public bool HasObjectId {
      get { return hasObjectId; }
    }
    [global::System.CLSCompliant(false)]
    public ulong ObjectId {
      get { return objectId_; }
    }
    
    public const int AccountIdFieldNumber = 2;
    private bool hasAccountId;
    private uint accountId_;
    public bool HasAccountId {
      get { return hasAccountId; }
    }
    [global::System.CLSCompliant(false)]
    public uint AccountId {
      get { return accountId_; }
    }
    
    public const int FirstNameFieldNumber = 3;
    private bool hasFirstName;
    private string firstName_ = "";
    public bool HasFirstName {
      get { return hasFirstName; }
    }
    public string FirstName {
      get { return firstName_; }
    }
    
    public const int SurNameFieldNumber = 4;
    private bool hasSurName;
    private string surName_ = "";
    public bool HasSurName {
      get { return hasSurName; }
    }
    public string SurName {
      get { return surName_; }
    }
    
    public const int BankCreditsFieldNumber = 5;
    private bool hasBankCredits;
    private uint bankCredits_;
    public bool HasBankCredits {
      get { return hasBankCredits; }
    }
    [global::System.CLSCompliant(false)]
    public uint BankCredits {
      get { return bankCredits_; }
    }
    
    public const int CashCreditsFieldNumber = 6;
    private bool hasCashCredits;
    private uint cashCredits_;
    public bool HasCashCredits {
      get { return hasCashCredits; }
    }
    [global::System.CLSCompliant(false)]
    public uint CashCredits {
      get { return cashCredits_; }
    }
    
    public const int BaseHealthFieldNumber = 7;
    private bool hasBaseHealth;
    private uint baseHealth_;
    public bool HasBaseHealth {
      get { return hasBaseHealth; }
    }
    [global::System.CLSCompliant(false)]
    public uint BaseHealth {
      get { return baseHealth_; }
    }
    
    public const int BaseActionFieldNumber = 8;
    private bool hasBaseAction;
    private uint baseAction_;
    public bool HasBaseAction {
      get { return hasBaseAction; }
    }
    [global::System.CLSCompliant(false)]
    public uint BaseAction {
      get { return baseAction_; }
    }
    
    public const int BaseMindFieldNumber = 10;
    private bool hasBaseMind;
    private uint baseMind_;
    public bool HasBaseMind {
      get { return hasBaseMind; }
    }
    [global::System.CLSCompliant(false)]
    public uint BaseMind {
      get { return baseMind_; }
    }
    
    public const int BiographyFieldNumber = 11;
    private bool hasBiography;
    private string biography_ = "";
    public bool HasBiography {
      get { return hasBiography; }
    }
    public string Biography {
      get { return biography_; }
    }
    
    public const int RemainingPlotsFieldNumber = 12;
    private bool hasRemainingPlots;
    private int remainingPlots_;
    public bool HasRemainingPlots {
      get { return hasRemainingPlots; }
    }
    public int RemainingPlots {
      get { return remainingPlots_; }
    }
    
    public const int MaximumimPlotsFieldNumber = 13;
    private bool hasMaximumimPlots;
    private int maximumimPlots_;
    public bool HasMaximumimPlots {
      get { return hasMaximumimPlots; }
    }
    public int MaximumimPlots {
      get { return maximumimPlots_; }
    }
    
    public const int TitleFieldNumber = 14;
    private bool hasTitle;
    private string title_ = "";
    public bool HasTitle {
      get { return hasTitle; }
    }
    public string Title {
      get { return title_; }
    }
    
    public const int InventoryItemsFieldNumber = 20;
    private pbc::PopsicleList<global::swgemurpcserver.rpc.CharacterInventoryItem> inventoryItems_ = new pbc::PopsicleList<global::swgemurpcserver.rpc.CharacterInventoryItem>();
    public scg::IList<global::swgemurpcserver.rpc.CharacterInventoryItem> InventoryItemsList {
      get { return inventoryItems_; }
    }
    public int InventoryItemsCount {
      get { return inventoryItems_.Count; }
    }
    public global::swgemurpcserver.rpc.CharacterInventoryItem GetInventoryItems(int index) {
      return inventoryItems_[index];
    }
    
    public const int StructuresFieldNumber = 21;
    private pbc::PopsicleList<global::swgemurpcserver.rpc.SWGEmuCharacterStructureItem> structures_ = new pbc::PopsicleList<global::swgemurpcserver.rpc.SWGEmuCharacterStructureItem>();
    public scg::IList<global::swgemurpcserver.rpc.SWGEmuCharacterStructureItem> StructuresList {
      get { return structures_; }
    }
    public int StructuresCount {
      get { return structures_.Count; }
    }
    public global::swgemurpcserver.rpc.SWGEmuCharacterStructureItem GetStructures(int index) {
      return structures_[index];
    }
    
    public override bool IsInitialized {
      get {
        if (!hasObjectId) return false;
        if (!hasAccountId) return false;
        if (!hasFirstName) return false;
        if (!hasSurName) return false;
        foreach (global::swgemurpcserver.rpc.CharacterInventoryItem element in InventoryItemsList) {
          if (!element.IsInitialized) return false;
        }
        foreach (global::swgemurpcserver.rpc.SWGEmuCharacterStructureItem element in StructuresList) {
          if (!element.IsInitialized) return false;
        }
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _sWGEmuCharacterDetailFieldNames;
      if (hasObjectId) {
        output.WriteFixed64(1, field_names[10], ObjectId);
      }
      if (hasAccountId) {
        output.WriteFixed32(2, field_names[0], AccountId);
      }
      if (hasFirstName) {
        output.WriteString(3, field_names[7], FirstName);
      }
      if (hasSurName) {
        output.WriteString(4, field_names[13], SurName);
      }
      if (hasBankCredits) {
        output.WriteFixed32(5, field_names[1], BankCredits);
      }
      if (hasCashCredits) {
        output.WriteFixed32(6, field_names[6], CashCredits);
      }
      if (hasBaseHealth) {
        output.WriteFixed32(7, field_names[3], BaseHealth);
      }
      if (hasBaseAction) {
        output.WriteFixed32(8, field_names[2], BaseAction);
      }
      if (hasBaseMind) {
        output.WriteFixed32(10, field_names[4], BaseMind);
      }
      if (hasBiography) {
        output.WriteString(11, field_names[5], Biography);
      }
      if (hasRemainingPlots) {
        output.WriteInt32(12, field_names[11], RemainingPlots);
      }
      if (hasMaximumimPlots) {
        output.WriteInt32(13, field_names[9], MaximumimPlots);
      }
      if (hasTitle) {
        output.WriteString(14, field_names[14], Title);
      }
      if (inventoryItems_.Count > 0) {
        output.WriteMessageArray(20, field_names[8], inventoryItems_);
      }
      if (structures_.Count > 0) {
        output.WriteMessageArray(21, field_names[12], structures_);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasObjectId) {
          size += pb::CodedOutputStream.ComputeFixed64Size(1, ObjectId);
        }
        if (hasAccountId) {
          size += pb::CodedOutputStream.ComputeFixed32Size(2, AccountId);
        }
        if (hasFirstName) {
          size += pb::CodedOutputStream.ComputeStringSize(3, FirstName);
        }
        if (hasSurName) {
          size += pb::CodedOutputStream.ComputeStringSize(4, SurName);
        }
        if (hasBankCredits) {
          size += pb::CodedOutputStream.ComputeFixed32Size(5, BankCredits);
        }
        if (hasCashCredits) {
          size += pb::CodedOutputStream.ComputeFixed32Size(6, CashCredits);
        }
        if (hasBaseHealth) {
          size += pb::CodedOutputStream.ComputeFixed32Size(7, BaseHealth);
        }
        if (hasBaseAction) {
          size += pb::CodedOutputStream.ComputeFixed32Size(8, BaseAction);
        }
        if (hasBaseMind) {
          size += pb::CodedOutputStream.ComputeFixed32Size(10, BaseMind);
        }
        if (hasBiography) {
          size += pb::CodedOutputStream.ComputeStringSize(11, Biography);
        }
        if (hasRemainingPlots) {
          size += pb::CodedOutputStream.ComputeInt32Size(12, RemainingPlots);
        }
        if (hasMaximumimPlots) {
          size += pb::CodedOutputStream.ComputeInt32Size(13, MaximumimPlots);
        }
        if (hasTitle) {
          size += pb::CodedOutputStream.ComputeStringSize(14, Title);
        }
        foreach (global::swgemurpcserver.rpc.CharacterInventoryItem element in InventoryItemsList) {
          size += pb::CodedOutputStream.ComputeMessageSize(20, element);
        }
        foreach (global::swgemurpcserver.rpc.SWGEmuCharacterStructureItem element in StructuresList) {
          size += pb::CodedOutputStream.ComputeMessageSize(21, element);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static SWGEmuCharacterDetail ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static SWGEmuCharacterDetail ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static SWGEmuCharacterDetail ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static SWGEmuCharacterDetail ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static SWGEmuCharacterDetail ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static SWGEmuCharacterDetail ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static SWGEmuCharacterDetail ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static SWGEmuCharacterDetail ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static SWGEmuCharacterDetail ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static SWGEmuCharacterDetail ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private SWGEmuCharacterDetail MakeReadOnly() {
      inventoryItems_.MakeReadOnly();
      structures_.MakeReadOnly();
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(SWGEmuCharacterDetail prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public sealed partial class Builder : pb::GeneratedBuilder<SWGEmuCharacterDetail, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(SWGEmuCharacterDetail cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private SWGEmuCharacterDetail result;
      
      private SWGEmuCharacterDetail PrepareBuilder() {
        if (resultIsReadOnly) {
          SWGEmuCharacterDetail original = result;
          result = new SWGEmuCharacterDetail();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override SWGEmuCharacterDetail MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::swgemurpcserver.rpc.SWGEmuCharacterDetail.Descriptor; }
      }
      
      public override SWGEmuCharacterDetail DefaultInstanceForType {
        get { return global::swgemurpcserver.rpc.SWGEmuCharacterDetail.DefaultInstance; }
      }
      
      public override SWGEmuCharacterDetail BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is SWGEmuCharacterDetail) {
          return MergeFrom((SWGEmuCharacterDetail) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(SWGEmuCharacterDetail other) {
        if (other == global::swgemurpcserver.rpc.SWGEmuCharacterDetail.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasObjectId) {
          ObjectId = other.ObjectId;
        }
        if (other.HasAccountId) {
          AccountId = other.AccountId;
        }
        if (other.HasFirstName) {
          FirstName = other.FirstName;
        }
        if (other.HasSurName) {
          SurName = other.SurName;
        }
        if (other.HasBankCredits) {
          BankCredits = other.BankCredits;
        }
        if (other.HasCashCredits) {
          CashCredits = other.CashCredits;
        }
        if (other.HasBaseHealth) {
          BaseHealth = other.BaseHealth;
        }
        if (other.HasBaseAction) {
          BaseAction = other.BaseAction;
        }
        if (other.HasBaseMind) {
          BaseMind = other.BaseMind;
        }
        if (other.HasBiography) {
          Biography = other.Biography;
        }
        if (other.HasRemainingPlots) {
          RemainingPlots = other.RemainingPlots;
        }
        if (other.HasMaximumimPlots) {
          MaximumimPlots = other.MaximumimPlots;
        }
        if (other.HasTitle) {
          Title = other.Title;
        }
        if (other.inventoryItems_.Count != 0) {
          result.inventoryItems_.Add(other.inventoryItems_);
        }
        if (other.structures_.Count != 0) {
          result.structures_.Add(other.structures_);
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_sWGEmuCharacterDetailFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _sWGEmuCharacterDetailFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 9: {
              result.hasObjectId = input.ReadFixed64(ref result.objectId_);
              break;
            }
            case 21: {
              result.hasAccountId = input.ReadFixed32(ref result.accountId_);
              break;
            }
            case 26: {
              result.hasFirstName = input.ReadString(ref result.firstName_);
              break;
            }
            case 34: {
              result.hasSurName = input.ReadString(ref result.surName_);
              break;
            }
            case 45: {
              result.hasBankCredits = input.ReadFixed32(ref result.bankCredits_);
              break;
            }
            case 53: {
              result.hasCashCredits = input.ReadFixed32(ref result.cashCredits_);
              break;
            }
            case 61: {
              result.hasBaseHealth = input.ReadFixed32(ref result.baseHealth_);
              break;
            }
            case 69: {
              result.hasBaseAction = input.ReadFixed32(ref result.baseAction_);
              break;
            }
            case 85: {
              result.hasBaseMind = input.ReadFixed32(ref result.baseMind_);
              break;
            }
            case 90: {
              result.hasBiography = input.ReadString(ref result.biography_);
              break;
            }
            case 96: {
              result.hasRemainingPlots = input.ReadInt32(ref result.remainingPlots_);
              break;
            }
            case 104: {
              result.hasMaximumimPlots = input.ReadInt32(ref result.maximumimPlots_);
              break;
            }
            case 114: {
              result.hasTitle = input.ReadString(ref result.title_);
              break;
            }
            case 162: {
              input.ReadMessageArray(tag, field_name, result.inventoryItems_, global::swgemurpcserver.rpc.CharacterInventoryItem.DefaultInstance, extensionRegistry);
              break;
            }
            case 170: {
              input.ReadMessageArray(tag, field_name, result.structures_, global::swgemurpcserver.rpc.SWGEmuCharacterStructureItem.DefaultInstance, extensionRegistry);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasObjectId {
        get { return result.hasObjectId; }
      }
      [global::System.CLSCompliant(false)]
      public ulong ObjectId {
        get { return result.ObjectId; }
        set { SetObjectId(value); }
      }
      [global::System.CLSCompliant(false)]
      public Builder SetObjectId(ulong value) {
        PrepareBuilder();
        result.hasObjectId = true;
        result.objectId_ = value;
        return this;
      }
      public Builder ClearObjectId() {
        PrepareBuilder();
        result.hasObjectId = false;
        result.objectId_ = 0;
        return this;
      }
      
      public bool HasAccountId {
        get { return result.hasAccountId; }
      }
      [global::System.CLSCompliant(false)]
      public uint AccountId {
        get { return result.AccountId; }
        set { SetAccountId(value); }
      }
      [global::System.CLSCompliant(false)]
      public Builder SetAccountId(uint value) {
        PrepareBuilder();
        result.hasAccountId = true;
        result.accountId_ = value;
        return this;
      }
      public Builder ClearAccountId() {
        PrepareBuilder();
        result.hasAccountId = false;
        result.accountId_ = 0;
        return this;
      }
      
      public bool HasFirstName {
        get { return result.hasFirstName; }
      }
      public string FirstName {
        get { return result.FirstName; }
        set { SetFirstName(value); }
      }
      public Builder SetFirstName(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasFirstName = true;
        result.firstName_ = value;
        return this;
      }
      public Builder ClearFirstName() {
        PrepareBuilder();
        result.hasFirstName = false;
        result.firstName_ = "";
        return this;
      }
      
      public bool HasSurName {
        get { return result.hasSurName; }
      }
      public string SurName {
        get { return result.SurName; }
        set { SetSurName(value); }
      }
      public Builder SetSurName(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasSurName = true;
        result.surName_ = value;
        return this;
      }
      public Builder ClearSurName() {
        PrepareBuilder();
        result.hasSurName = false;
        result.surName_ = "";
        return this;
      }
      
      public bool HasBankCredits {
        get { return result.hasBankCredits; }
      }
      [global::System.CLSCompliant(false)]
      public uint BankCredits {
        get { return result.BankCredits; }
        set { SetBankCredits(value); }
      }
      [global::System.CLSCompliant(false)]
      public Builder SetBankCredits(uint value) {
        PrepareBuilder();
        result.hasBankCredits = true;
        result.bankCredits_ = value;
        return this;
      }
      public Builder ClearBankCredits() {
        PrepareBuilder();
        result.hasBankCredits = false;
        result.bankCredits_ = 0;
        return this;
      }
      
      public bool HasCashCredits {
        get { return result.hasCashCredits; }
      }
      [global::System.CLSCompliant(false)]
      public uint CashCredits {
        get { return result.CashCredits; }
        set { SetCashCredits(value); }
      }
      [global::System.CLSCompliant(false)]
      public Builder SetCashCredits(uint value) {
        PrepareBuilder();
        result.hasCashCredits = true;
        result.cashCredits_ = value;
        return this;
      }
      public Builder ClearCashCredits() {
        PrepareBuilder();
        result.hasCashCredits = false;
        result.cashCredits_ = 0;
        return this;
      }
      
      public bool HasBaseHealth {
        get { return result.hasBaseHealth; }
      }
      [global::System.CLSCompliant(false)]
      public uint BaseHealth {
        get { return result.BaseHealth; }
        set { SetBaseHealth(value); }
      }
      [global::System.CLSCompliant(false)]
      public Builder SetBaseHealth(uint value) {
        PrepareBuilder();
        result.hasBaseHealth = true;
        result.baseHealth_ = value;
        return this;
      }
      public Builder ClearBaseHealth() {
        PrepareBuilder();
        result.hasBaseHealth = false;
        result.baseHealth_ = 0;
        return this;
      }
      
      public bool HasBaseAction {
        get { return result.hasBaseAction; }
      }
      [global::System.CLSCompliant(false)]
      public uint BaseAction {
        get { return result.BaseAction; }
        set { SetBaseAction(value); }
      }
      [global::System.CLSCompliant(false)]
      public Builder SetBaseAction(uint value) {
        PrepareBuilder();
        result.hasBaseAction = true;
        result.baseAction_ = value;
        return this;
      }
      public Builder ClearBaseAction() {
        PrepareBuilder();
        result.hasBaseAction = false;
        result.baseAction_ = 0;
        return this;
      }
      
      public bool HasBaseMind {
        get { return result.hasBaseMind; }
      }
      [global::System.CLSCompliant(false)]
      public uint BaseMind {
        get { return result.BaseMind; }
        set { SetBaseMind(value); }
      }
      [global::System.CLSCompliant(false)]
      public Builder SetBaseMind(uint value) {
        PrepareBuilder();
        result.hasBaseMind = true;
        result.baseMind_ = value;
        return this;
      }
      public Builder ClearBaseMind() {
        PrepareBuilder();
        result.hasBaseMind = false;
        result.baseMind_ = 0;
        return this;
      }
      
      public bool HasBiography {
        get { return result.hasBiography; }
      }
      public string Biography {
        get { return result.Biography; }
        set { SetBiography(value); }
      }
      public Builder SetBiography(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasBiography = true;
        result.biography_ = value;
        return this;
      }
      public Builder ClearBiography() {
        PrepareBuilder();
        result.hasBiography = false;
        result.biography_ = "";
        return this;
      }
      
      public bool HasRemainingPlots {
        get { return result.hasRemainingPlots; }
      }
      public int RemainingPlots {
        get { return result.RemainingPlots; }
        set { SetRemainingPlots(value); }
      }
      public Builder SetRemainingPlots(int value) {
        PrepareBuilder();
        result.hasRemainingPlots = true;
        result.remainingPlots_ = value;
        return this;
      }
      public Builder ClearRemainingPlots() {
        PrepareBuilder();
        result.hasRemainingPlots = false;
        result.remainingPlots_ = 0;
        return this;
      }
      
      public bool HasMaximumimPlots {
        get { return result.hasMaximumimPlots; }
      }
      public int MaximumimPlots {
        get { return result.MaximumimPlots; }
        set { SetMaximumimPlots(value); }
      }
      public Builder SetMaximumimPlots(int value) {
        PrepareBuilder();
        result.hasMaximumimPlots = true;
        result.maximumimPlots_ = value;
        return this;
      }
      public Builder ClearMaximumimPlots() {
        PrepareBuilder();
        result.hasMaximumimPlots = false;
        result.maximumimPlots_ = 0;
        return this;
      }
      
      public bool HasTitle {
        get { return result.hasTitle; }
      }
      public string Title {
        get { return result.Title; }
        set { SetTitle(value); }
      }
      public Builder SetTitle(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasTitle = true;
        result.title_ = value;
        return this;
      }
      public Builder ClearTitle() {
        PrepareBuilder();
        result.hasTitle = false;
        result.title_ = "";
        return this;
      }
      
      public pbc::IPopsicleList<global::swgemurpcserver.rpc.CharacterInventoryItem> InventoryItemsList {
        get { return PrepareBuilder().inventoryItems_; }
      }
      public int InventoryItemsCount {
        get { return result.InventoryItemsCount; }
      }
      public global::swgemurpcserver.rpc.CharacterInventoryItem GetInventoryItems(int index) {
        return result.GetInventoryItems(index);
      }
      public Builder SetInventoryItems(int index, global::swgemurpcserver.rpc.CharacterInventoryItem value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.inventoryItems_[index] = value;
        return this;
      }
      public Builder SetInventoryItems(int index, global::swgemurpcserver.rpc.CharacterInventoryItem.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        PrepareBuilder();
        result.inventoryItems_[index] = builderForValue.Build();
        return this;
      }
      public Builder AddInventoryItems(global::swgemurpcserver.rpc.CharacterInventoryItem value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.inventoryItems_.Add(value);
        return this;
      }
      public Builder AddInventoryItems(global::swgemurpcserver.rpc.CharacterInventoryItem.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        PrepareBuilder();
        result.inventoryItems_.Add(builderForValue.Build());
        return this;
      }
      public Builder AddRangeInventoryItems(scg::IEnumerable<global::swgemurpcserver.rpc.CharacterInventoryItem> values) {
        PrepareBuilder();
        result.inventoryItems_.Add(values);
        return this;
      }
      public Builder ClearInventoryItems() {
        PrepareBuilder();
        result.inventoryItems_.Clear();
        return this;
      }
      
      public pbc::IPopsicleList<global::swgemurpcserver.rpc.SWGEmuCharacterStructureItem> StructuresList {
        get { return PrepareBuilder().structures_; }
      }
      public int StructuresCount {
        get { return result.StructuresCount; }
      }
      public global::swgemurpcserver.rpc.SWGEmuCharacterStructureItem GetStructures(int index) {
        return result.GetStructures(index);
      }
      public Builder SetStructures(int index, global::swgemurpcserver.rpc.SWGEmuCharacterStructureItem value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.structures_[index] = value;
        return this;
      }
      public Builder SetStructures(int index, global::swgemurpcserver.rpc.SWGEmuCharacterStructureItem.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        PrepareBuilder();
        result.structures_[index] = builderForValue.Build();
        return this;
      }
      public Builder AddStructures(global::swgemurpcserver.rpc.SWGEmuCharacterStructureItem value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.structures_.Add(value);
        return this;
      }
      public Builder AddStructures(global::swgemurpcserver.rpc.SWGEmuCharacterStructureItem.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        PrepareBuilder();
        result.structures_.Add(builderForValue.Build());
        return this;
      }
      public Builder AddRangeStructures(scg::IEnumerable<global::swgemurpcserver.rpc.SWGEmuCharacterStructureItem> values) {
        PrepareBuilder();
        result.structures_.Add(values);
        return this;
      }
      public Builder ClearStructures() {
        PrepareBuilder();
        result.structures_.Clear();
        return this;
      }
    }
    static SWGEmuCharacterDetail() {
      object.ReferenceEquals(global::swgemurpcserver.rpc.CharacterDetails.Descriptor, null);
    }
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public sealed partial class SWGEmuCharacterStructureItem : pb::GeneratedMessage<SWGEmuCharacterStructureItem, SWGEmuCharacterStructureItem.Builder> {
    private SWGEmuCharacterStructureItem() { }
    private static readonly SWGEmuCharacterStructureItem defaultInstance = new SWGEmuCharacterStructureItem().MakeReadOnly();
    private static readonly string[] _sWGEmuCharacterStructureItemFieldNames = new string[] { "display_name", "object_id", "object_name" };
    private static readonly uint[] _sWGEmuCharacterStructureItemFieldTags = new uint[] { 26, 9, 18 };
    public static SWGEmuCharacterStructureItem DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override SWGEmuCharacterStructureItem DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override SWGEmuCharacterStructureItem ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::swgemurpcserver.rpc.CharacterDetails.internal__static_swgemurpcserver_rpc_SWGEmuCharacterStructureItem__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<SWGEmuCharacterStructureItem, SWGEmuCharacterStructureItem.Builder> InternalFieldAccessors {
      get { return global::swgemurpcserver.rpc.CharacterDetails.internal__static_swgemurpcserver_rpc_SWGEmuCharacterStructureItem__FieldAccessorTable; }
    }
    
    public const int ObjectIdFieldNumber = 1;
    private bool hasObjectId;
    private ulong objectId_;
    public bool HasObjectId {
      get { return hasObjectId; }
    }
    [global::System.CLSCompliant(false)]
    public ulong ObjectId {
      get { return objectId_; }
    }
    
    public const int ObjectNameFieldNumber = 2;
    private bool hasObjectName;
    private string objectName_ = "";
    public bool HasObjectName {
      get { return hasObjectName; }
    }
    public string ObjectName {
      get { return objectName_; }
    }
    
    public const int DisplayNameFieldNumber = 3;
    private bool hasDisplayName;
    private string displayName_ = "";
    public bool HasDisplayName {
      get { return hasDisplayName; }
    }
    public string DisplayName {
      get { return displayName_; }
    }
    
    public override bool IsInitialized {
      get {
        if (!hasObjectId) return false;
        if (!hasObjectName) return false;
        if (!hasDisplayName) return false;
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _sWGEmuCharacterStructureItemFieldNames;
      if (hasObjectId) {
        output.WriteFixed64(1, field_names[1], ObjectId);
      }
      if (hasObjectName) {
        output.WriteString(2, field_names[2], ObjectName);
      }
      if (hasDisplayName) {
        output.WriteString(3, field_names[0], DisplayName);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasObjectId) {
          size += pb::CodedOutputStream.ComputeFixed64Size(1, ObjectId);
        }
        if (hasObjectName) {
          size += pb::CodedOutputStream.ComputeStringSize(2, ObjectName);
        }
        if (hasDisplayName) {
          size += pb::CodedOutputStream.ComputeStringSize(3, DisplayName);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static SWGEmuCharacterStructureItem ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static SWGEmuCharacterStructureItem ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static SWGEmuCharacterStructureItem ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static SWGEmuCharacterStructureItem ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static SWGEmuCharacterStructureItem ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static SWGEmuCharacterStructureItem ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static SWGEmuCharacterStructureItem ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static SWGEmuCharacterStructureItem ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static SWGEmuCharacterStructureItem ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static SWGEmuCharacterStructureItem ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private SWGEmuCharacterStructureItem MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(SWGEmuCharacterStructureItem prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public sealed partial class Builder : pb::GeneratedBuilder<SWGEmuCharacterStructureItem, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(SWGEmuCharacterStructureItem cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private SWGEmuCharacterStructureItem result;
      
      private SWGEmuCharacterStructureItem PrepareBuilder() {
        if (resultIsReadOnly) {
          SWGEmuCharacterStructureItem original = result;
          result = new SWGEmuCharacterStructureItem();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override SWGEmuCharacterStructureItem MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::swgemurpcserver.rpc.SWGEmuCharacterStructureItem.Descriptor; }
      }
      
      public override SWGEmuCharacterStructureItem DefaultInstanceForType {
        get { return global::swgemurpcserver.rpc.SWGEmuCharacterStructureItem.DefaultInstance; }
      }
      
      public override SWGEmuCharacterStructureItem BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is SWGEmuCharacterStructureItem) {
          return MergeFrom((SWGEmuCharacterStructureItem) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(SWGEmuCharacterStructureItem other) {
        if (other == global::swgemurpcserver.rpc.SWGEmuCharacterStructureItem.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasObjectId) {
          ObjectId = other.ObjectId;
        }
        if (other.HasObjectName) {
          ObjectName = other.ObjectName;
        }
        if (other.HasDisplayName) {
          DisplayName = other.DisplayName;
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_sWGEmuCharacterStructureItemFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _sWGEmuCharacterStructureItemFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 9: {
              result.hasObjectId = input.ReadFixed64(ref result.objectId_);
              break;
            }
            case 18: {
              result.hasObjectName = input.ReadString(ref result.objectName_);
              break;
            }
            case 26: {
              result.hasDisplayName = input.ReadString(ref result.displayName_);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasObjectId {
        get { return result.hasObjectId; }
      }
      [global::System.CLSCompliant(false)]
      public ulong ObjectId {
        get { return result.ObjectId; }
        set { SetObjectId(value); }
      }
      [global::System.CLSCompliant(false)]
      public Builder SetObjectId(ulong value) {
        PrepareBuilder();
        result.hasObjectId = true;
        result.objectId_ = value;
        return this;
      }
      public Builder ClearObjectId() {
        PrepareBuilder();
        result.hasObjectId = false;
        result.objectId_ = 0;
        return this;
      }
      
      public bool HasObjectName {
        get { return result.hasObjectName; }
      }
      public string ObjectName {
        get { return result.ObjectName; }
        set { SetObjectName(value); }
      }
      public Builder SetObjectName(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasObjectName = true;
        result.objectName_ = value;
        return this;
      }
      public Builder ClearObjectName() {
        PrepareBuilder();
        result.hasObjectName = false;
        result.objectName_ = "";
        return this;
      }
      
      public bool HasDisplayName {
        get { return result.hasDisplayName; }
      }
      public string DisplayName {
        get { return result.DisplayName; }
        set { SetDisplayName(value); }
      }
      public Builder SetDisplayName(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasDisplayName = true;
        result.displayName_ = value;
        return this;
      }
      public Builder ClearDisplayName() {
        PrepareBuilder();
        result.hasDisplayName = false;
        result.displayName_ = "";
        return this;
      }
    }
    static SWGEmuCharacterStructureItem() {
      object.ReferenceEquals(global::swgemurpcserver.rpc.CharacterDetails.Descriptor, null);
    }
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public sealed partial class GetCharacterDetailsRequest : pb::GeneratedMessage<GetCharacterDetailsRequest, GetCharacterDetailsRequest.Builder> {
    private GetCharacterDetailsRequest() { }
    private static readonly GetCharacterDetailsRequest defaultInstance = new GetCharacterDetailsRequest().MakeReadOnly();
    private static readonly string[] _getCharacterDetailsRequestFieldNames = new string[] { "account_id", "first_name", "galaxy_id", "galaxy_name", "object_id", "sur_name" };
    private static readonly uint[] _getCharacterDetailsRequestFieldTags = new uint[] { 13, 58, 29, 74, 17, 66 };
    public static GetCharacterDetailsRequest DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override GetCharacterDetailsRequest DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override GetCharacterDetailsRequest ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::swgemurpcserver.rpc.CharacterDetails.internal__static_swgemurpcserver_rpc_GetCharacterDetailsRequest__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<GetCharacterDetailsRequest, GetCharacterDetailsRequest.Builder> InternalFieldAccessors {
      get { return global::swgemurpcserver.rpc.CharacterDetails.internal__static_swgemurpcserver_rpc_GetCharacterDetailsRequest__FieldAccessorTable; }
    }
    
    public const int AccountIdFieldNumber = 1;
    private bool hasAccountId;
    private uint accountId_;
    public bool HasAccountId {
      get { return hasAccountId; }
    }
    [global::System.CLSCompliant(false)]
    public uint AccountId {
      get { return accountId_; }
    }
    
    public const int ObjectIdFieldNumber = 2;
    private bool hasObjectId;
    private ulong objectId_;
    public bool HasObjectId {
      get { return hasObjectId; }
    }
    [global::System.CLSCompliant(false)]
    public ulong ObjectId {
      get { return objectId_; }
    }
    
    public const int GalaxyIdFieldNumber = 3;
    private bool hasGalaxyId;
    private uint galaxyId_;
    public bool HasGalaxyId {
      get { return hasGalaxyId; }
    }
    [global::System.CLSCompliant(false)]
    public uint GalaxyId {
      get { return galaxyId_; }
    }
    
    public const int FirstNameFieldNumber = 7;
    private bool hasFirstName;
    private string firstName_ = "";
    public bool HasFirstName {
      get { return hasFirstName; }
    }
    public string FirstName {
      get { return firstName_; }
    }
    
    public const int SurNameFieldNumber = 8;
    private bool hasSurName;
    private string surName_ = "";
    public bool HasSurName {
      get { return hasSurName; }
    }
    public string SurName {
      get { return surName_; }
    }
    
    public const int GalaxyNameFieldNumber = 9;
    private bool hasGalaxyName;
    private string galaxyName_ = "";
    public bool HasGalaxyName {
      get { return hasGalaxyName; }
    }
    public string GalaxyName {
      get { return galaxyName_; }
    }
    
    public override bool IsInitialized {
      get {
        if (!hasAccountId) return false;
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _getCharacterDetailsRequestFieldNames;
      if (hasAccountId) {
        output.WriteFixed32(1, field_names[0], AccountId);
      }
      if (hasObjectId) {
        output.WriteFixed64(2, field_names[4], ObjectId);
      }
      if (hasGalaxyId) {
        output.WriteFixed32(3, field_names[2], GalaxyId);
      }
      if (hasFirstName) {
        output.WriteString(7, field_names[1], FirstName);
      }
      if (hasSurName) {
        output.WriteString(8, field_names[5], SurName);
      }
      if (hasGalaxyName) {
        output.WriteString(9, field_names[3], GalaxyName);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasAccountId) {
          size += pb::CodedOutputStream.ComputeFixed32Size(1, AccountId);
        }
        if (hasObjectId) {
          size += pb::CodedOutputStream.ComputeFixed64Size(2, ObjectId);
        }
        if (hasGalaxyId) {
          size += pb::CodedOutputStream.ComputeFixed32Size(3, GalaxyId);
        }
        if (hasFirstName) {
          size += pb::CodedOutputStream.ComputeStringSize(7, FirstName);
        }
        if (hasSurName) {
          size += pb::CodedOutputStream.ComputeStringSize(8, SurName);
        }
        if (hasGalaxyName) {
          size += pb::CodedOutputStream.ComputeStringSize(9, GalaxyName);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static GetCharacterDetailsRequest ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static GetCharacterDetailsRequest ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static GetCharacterDetailsRequest ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static GetCharacterDetailsRequest ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static GetCharacterDetailsRequest ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static GetCharacterDetailsRequest ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static GetCharacterDetailsRequest ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static GetCharacterDetailsRequest ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static GetCharacterDetailsRequest ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static GetCharacterDetailsRequest ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private GetCharacterDetailsRequest MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(GetCharacterDetailsRequest prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public sealed partial class Builder : pb::GeneratedBuilder<GetCharacterDetailsRequest, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(GetCharacterDetailsRequest cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private GetCharacterDetailsRequest result;
      
      private GetCharacterDetailsRequest PrepareBuilder() {
        if (resultIsReadOnly) {
          GetCharacterDetailsRequest original = result;
          result = new GetCharacterDetailsRequest();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override GetCharacterDetailsRequest MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::swgemurpcserver.rpc.GetCharacterDetailsRequest.Descriptor; }
      }
      
      public override GetCharacterDetailsRequest DefaultInstanceForType {
        get { return global::swgemurpcserver.rpc.GetCharacterDetailsRequest.DefaultInstance; }
      }
      
      public override GetCharacterDetailsRequest BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is GetCharacterDetailsRequest) {
          return MergeFrom((GetCharacterDetailsRequest) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(GetCharacterDetailsRequest other) {
        if (other == global::swgemurpcserver.rpc.GetCharacterDetailsRequest.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasAccountId) {
          AccountId = other.AccountId;
        }
        if (other.HasObjectId) {
          ObjectId = other.ObjectId;
        }
        if (other.HasGalaxyId) {
          GalaxyId = other.GalaxyId;
        }
        if (other.HasFirstName) {
          FirstName = other.FirstName;
        }
        if (other.HasSurName) {
          SurName = other.SurName;
        }
        if (other.HasGalaxyName) {
          GalaxyName = other.GalaxyName;
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_getCharacterDetailsRequestFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _getCharacterDetailsRequestFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 13: {
              result.hasAccountId = input.ReadFixed32(ref result.accountId_);
              break;
            }
            case 17: {
              result.hasObjectId = input.ReadFixed64(ref result.objectId_);
              break;
            }
            case 29: {
              result.hasGalaxyId = input.ReadFixed32(ref result.galaxyId_);
              break;
            }
            case 58: {
              result.hasFirstName = input.ReadString(ref result.firstName_);
              break;
            }
            case 66: {
              result.hasSurName = input.ReadString(ref result.surName_);
              break;
            }
            case 74: {
              result.hasGalaxyName = input.ReadString(ref result.galaxyName_);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasAccountId {
        get { return result.hasAccountId; }
      }
      [global::System.CLSCompliant(false)]
      public uint AccountId {
        get { return result.AccountId; }
        set { SetAccountId(value); }
      }
      [global::System.CLSCompliant(false)]
      public Builder SetAccountId(uint value) {
        PrepareBuilder();
        result.hasAccountId = true;
        result.accountId_ = value;
        return this;
      }
      public Builder ClearAccountId() {
        PrepareBuilder();
        result.hasAccountId = false;
        result.accountId_ = 0;
        return this;
      }
      
      public bool HasObjectId {
        get { return result.hasObjectId; }
      }
      [global::System.CLSCompliant(false)]
      public ulong ObjectId {
        get { return result.ObjectId; }
        set { SetObjectId(value); }
      }
      [global::System.CLSCompliant(false)]
      public Builder SetObjectId(ulong value) {
        PrepareBuilder();
        result.hasObjectId = true;
        result.objectId_ = value;
        return this;
      }
      public Builder ClearObjectId() {
        PrepareBuilder();
        result.hasObjectId = false;
        result.objectId_ = 0;
        return this;
      }
      
      public bool HasGalaxyId {
        get { return result.hasGalaxyId; }
      }
      [global::System.CLSCompliant(false)]
      public uint GalaxyId {
        get { return result.GalaxyId; }
        set { SetGalaxyId(value); }
      }
      [global::System.CLSCompliant(false)]
      public Builder SetGalaxyId(uint value) {
        PrepareBuilder();
        result.hasGalaxyId = true;
        result.galaxyId_ = value;
        return this;
      }
      public Builder ClearGalaxyId() {
        PrepareBuilder();
        result.hasGalaxyId = false;
        result.galaxyId_ = 0;
        return this;
      }
      
      public bool HasFirstName {
        get { return result.hasFirstName; }
      }
      public string FirstName {
        get { return result.FirstName; }
        set { SetFirstName(value); }
      }
      public Builder SetFirstName(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasFirstName = true;
        result.firstName_ = value;
        return this;
      }
      public Builder ClearFirstName() {
        PrepareBuilder();
        result.hasFirstName = false;
        result.firstName_ = "";
        return this;
      }
      
      public bool HasSurName {
        get { return result.hasSurName; }
      }
      public string SurName {
        get { return result.SurName; }
        set { SetSurName(value); }
      }
      public Builder SetSurName(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasSurName = true;
        result.surName_ = value;
        return this;
      }
      public Builder ClearSurName() {
        PrepareBuilder();
        result.hasSurName = false;
        result.surName_ = "";
        return this;
      }
      
      public bool HasGalaxyName {
        get { return result.hasGalaxyName; }
      }
      public string GalaxyName {
        get { return result.GalaxyName; }
        set { SetGalaxyName(value); }
      }
      public Builder SetGalaxyName(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasGalaxyName = true;
        result.galaxyName_ = value;
        return this;
      }
      public Builder ClearGalaxyName() {
        PrepareBuilder();
        result.hasGalaxyName = false;
        result.galaxyName_ = "";
        return this;
      }
    }
    static GetCharacterDetailsRequest() {
      object.ReferenceEquals(global::swgemurpcserver.rpc.CharacterDetails.Descriptor, null);
    }
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public sealed partial class GetCharacterDetailsResponse : pb::GeneratedMessage<GetCharacterDetailsResponse, GetCharacterDetailsResponse.Builder> {
    private GetCharacterDetailsResponse() { }
    private static readonly GetCharacterDetailsResponse defaultInstance = new GetCharacterDetailsResponse().MakeReadOnly();
    private static readonly string[] _getCharacterDetailsResponseFieldNames = new string[] { "character_details" };
    private static readonly uint[] _getCharacterDetailsResponseFieldTags = new uint[] { 10 };
    public static GetCharacterDetailsResponse DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override GetCharacterDetailsResponse DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override GetCharacterDetailsResponse ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::swgemurpcserver.rpc.CharacterDetails.internal__static_swgemurpcserver_rpc_GetCharacterDetailsResponse__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<GetCharacterDetailsResponse, GetCharacterDetailsResponse.Builder> InternalFieldAccessors {
      get { return global::swgemurpcserver.rpc.CharacterDetails.internal__static_swgemurpcserver_rpc_GetCharacterDetailsResponse__FieldAccessorTable; }
    }
    
    public const int CharacterDetailsFieldNumber = 1;
    private pbc::PopsicleList<global::swgemurpcserver.rpc.SWGEmuCharacterDetail> characterDetails_ = new pbc::PopsicleList<global::swgemurpcserver.rpc.SWGEmuCharacterDetail>();
    public scg::IList<global::swgemurpcserver.rpc.SWGEmuCharacterDetail> CharacterDetailsList {
      get { return characterDetails_; }
    }
    public int CharacterDetailsCount {
      get { return characterDetails_.Count; }
    }
    public global::swgemurpcserver.rpc.SWGEmuCharacterDetail GetCharacterDetails(int index) {
      return characterDetails_[index];
    }
    
    public override bool IsInitialized {
      get {
        foreach (global::swgemurpcserver.rpc.SWGEmuCharacterDetail element in CharacterDetailsList) {
          if (!element.IsInitialized) return false;
        }
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _getCharacterDetailsResponseFieldNames;
      if (characterDetails_.Count > 0) {
        output.WriteMessageArray(1, field_names[0], characterDetails_);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        foreach (global::swgemurpcserver.rpc.SWGEmuCharacterDetail element in CharacterDetailsList) {
          size += pb::CodedOutputStream.ComputeMessageSize(1, element);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static GetCharacterDetailsResponse ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static GetCharacterDetailsResponse ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static GetCharacterDetailsResponse ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static GetCharacterDetailsResponse ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static GetCharacterDetailsResponse ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static GetCharacterDetailsResponse ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static GetCharacterDetailsResponse ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static GetCharacterDetailsResponse ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static GetCharacterDetailsResponse ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static GetCharacterDetailsResponse ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private GetCharacterDetailsResponse MakeReadOnly() {
      characterDetails_.MakeReadOnly();
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(GetCharacterDetailsResponse prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public sealed partial class Builder : pb::GeneratedBuilder<GetCharacterDetailsResponse, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(GetCharacterDetailsResponse cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private GetCharacterDetailsResponse result;
      
      private GetCharacterDetailsResponse PrepareBuilder() {
        if (resultIsReadOnly) {
          GetCharacterDetailsResponse original = result;
          result = new GetCharacterDetailsResponse();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override GetCharacterDetailsResponse MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::swgemurpcserver.rpc.GetCharacterDetailsResponse.Descriptor; }
      }
      
      public override GetCharacterDetailsResponse DefaultInstanceForType {
        get { return global::swgemurpcserver.rpc.GetCharacterDetailsResponse.DefaultInstance; }
      }
      
      public override GetCharacterDetailsResponse BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is GetCharacterDetailsResponse) {
          return MergeFrom((GetCharacterDetailsResponse) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(GetCharacterDetailsResponse other) {
        if (other == global::swgemurpcserver.rpc.GetCharacterDetailsResponse.DefaultInstance) return this;
        PrepareBuilder();
        if (other.characterDetails_.Count != 0) {
          result.characterDetails_.Add(other.characterDetails_);
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_getCharacterDetailsResponseFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _getCharacterDetailsResponseFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 10: {
              input.ReadMessageArray(tag, field_name, result.characterDetails_, global::swgemurpcserver.rpc.SWGEmuCharacterDetail.DefaultInstance, extensionRegistry);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public pbc::IPopsicleList<global::swgemurpcserver.rpc.SWGEmuCharacterDetail> CharacterDetailsList {
        get { return PrepareBuilder().characterDetails_; }
      }
      public int CharacterDetailsCount {
        get { return result.CharacterDetailsCount; }
      }
      public global::swgemurpcserver.rpc.SWGEmuCharacterDetail GetCharacterDetails(int index) {
        return result.GetCharacterDetails(index);
      }
      public Builder SetCharacterDetails(int index, global::swgemurpcserver.rpc.SWGEmuCharacterDetail value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.characterDetails_[index] = value;
        return this;
      }
      public Builder SetCharacterDetails(int index, global::swgemurpcserver.rpc.SWGEmuCharacterDetail.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        PrepareBuilder();
        result.characterDetails_[index] = builderForValue.Build();
        return this;
      }
      public Builder AddCharacterDetails(global::swgemurpcserver.rpc.SWGEmuCharacterDetail value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.characterDetails_.Add(value);
        return this;
      }
      public Builder AddCharacterDetails(global::swgemurpcserver.rpc.SWGEmuCharacterDetail.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        PrepareBuilder();
        result.characterDetails_.Add(builderForValue.Build());
        return this;
      }
      public Builder AddRangeCharacterDetails(scg::IEnumerable<global::swgemurpcserver.rpc.SWGEmuCharacterDetail> values) {
        PrepareBuilder();
        result.characterDetails_.Add(values);
        return this;
      }
      public Builder ClearCharacterDetails() {
        PrepareBuilder();
        result.characterDetails_.Clear();
        return this;
      }
    }
    static GetCharacterDetailsResponse() {
      object.ReferenceEquals(global::swgemurpcserver.rpc.CharacterDetails.Descriptor, null);
    }
  }
  
  #endregion
  
  #region Services
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
  public abstract class SWGEmuCharacterDetailsService : pb::IService {
    public abstract void GetCharacterDetails(
        pb::IRpcController controller,
        global::swgemurpcserver.rpc.GetCharacterDetailsRequest request,
        global::System.Action<global::swgemurpcserver.rpc.GetCharacterDetailsResponse> done);
    
    public static pbd::ServiceDescriptor Descriptor {
      get { return CharacterDetails.Descriptor.Services[0]; }
    }
    public pbd::ServiceDescriptor DescriptorForType {
      get { return Descriptor; }
    }
    
    public void CallMethod(
        pbd::MethodDescriptor method,
        pb::IRpcController controller,
        pb::IMessage request,
        global::System.Action<pb::IMessage> done) {
      if (method.Service != Descriptor) {
        throw new global::System.ArgumentException(
            "Service.CallMethod() given method descriptor for wrong service type.");
      }
      switch(method.Index) {
        case 0:
          this.GetCharacterDetails(controller, (global::swgemurpcserver.rpc.GetCharacterDetailsRequest) request,
              pb::RpcUtil.SpecializeCallback<global::swgemurpcserver.rpc.GetCharacterDetailsResponse>(
              done));
          return;
        default:
          throw new global::System.InvalidOperationException("Can't get here.");
      }
    }
    
    public pb::IMessage GetRequestPrototype(pbd::MethodDescriptor method) {
      if (method.Service != Descriptor) {
        throw new global::System.ArgumentException(
            "Service.GetRequestPrototype() given method descriptor for wrong service type.");
      }
      switch(method.Index) {
        case 0:
          return global::swgemurpcserver.rpc.GetCharacterDetailsRequest.DefaultInstance;
        default:
          throw new global::System.InvalidOperationException("Can't get here.");
      }
    }
    
    public pb::IMessage GetResponsePrototype(pbd::MethodDescriptor method) {
      if (method.Service != Descriptor) {
        throw new global::System.ArgumentException(
            "Service.GetResponsePrototype() given method descriptor for wrong service type.");
      }
      switch(method.Index) {
        case 0:
          return global::swgemurpcserver.rpc.GetCharacterDetailsResponse.DefaultInstance;
        default:
          throw new global::System.InvalidOperationException("Can't get here.");
      }
    }
    
    public static Stub CreateStub(pb::IRpcChannel channel) {
      return new Stub(channel);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.4.1.473")]
    public class Stub : global::swgemurpcserver.rpc.SWGEmuCharacterDetailsService {
      internal Stub(pb::IRpcChannel channel) {
        this.channel = channel;
      }
      
      private readonly pb::IRpcChannel channel;
      
      public pb::IRpcChannel Channel {
        get { return channel; }
      }
      
      public override void GetCharacterDetails(
          pb::IRpcController controller,
          global::swgemurpcserver.rpc.GetCharacterDetailsRequest request,
          global::System.Action<global::swgemurpcserver.rpc.GetCharacterDetailsResponse> done) {
        channel.CallMethod(Descriptor.Methods[0],
            controller, request, global::swgemurpcserver.rpc.GetCharacterDetailsResponse.DefaultInstance,
            pb::RpcUtil.GeneralizeCallback<global::swgemurpcserver.rpc.GetCharacterDetailsResponse, global::swgemurpcserver.rpc.GetCharacterDetailsResponse.Builder>(done, global::swgemurpcserver.rpc.GetCharacterDetailsResponse.DefaultInstance));
      }
    }
  }
  #endregion
  
}

#endregion Designer generated code
